### ISSUE TITLE
UserParameter=pfsense.mbuf.ptotal

### ISSUE THREAD

**Issue by matth94** [keentonsas/zabbix-template-pfsense#1]
Bonjour,

Votre template fait référence à pfsense.mbuf.ptotal mais celui-ci n'est pas mis dans les userparameter du readme. Est-ce un oubli?

Merci d'avance.

**Comment by keentonsas** [comment]
Bonjour,

C'est un item calculé à partir de 3 autres items, donc pas besoin de UserParameter pour celui-ci.

Désolé pour le temps de réponse ✌️ 

++
